package prd

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/mistakeknot/autarch/internal/coldwine/storage"
)

func TestImportFromBriefs(t *testing.T) {
	// Create a temporary directory structure
	tmpDir := t.TempDir()
	briefsDir := filepath.Join(tmpDir, ".gurgeh", "briefs", "PRD-001")
	if err := os.MkdirAll(briefsDir, 0o755); err != nil {
		t.Fatal(err)
	}

	// Create test brief files
	brief1 := `# Implement User Authentication

## Outcome
Users can log in and out of the application securely.

## Acceptance Criteria
- [ ] Login form accepts email and password
- [ ] Session persists across page refreshes
- [ ] Logout clears session
---
*Brief generated by Gurgeh.*
`
	brief2 := `# Add Password Reset Flow

## Outcome
Users who forget their password can reset it via email.

## Acceptance Criteria
- [ ] Reset link sent to email
- [ ] Link expires after 24 hours
`
	if err := os.WriteFile(filepath.Join(briefsDir, "BRIEF-001-implement-auth.md"), []byte(brief1), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(briefsDir, "BRIEF-002-password-reset.md"), []byte(brief2), 0o644); err != nil {
		t.Fatal(err)
	}

	// Test import
	result, err := ImportFromBriefs(BriefImportOptions{
		Root:   tmpDir,
		SpecID: "PRD-001",
	})
	if err != nil {
		t.Fatalf("ImportFromBriefs failed: %v", err)
	}

	// Verify result
	if len(result.Tasks) != 2 {
		t.Fatalf("Expected 2 tasks, got %d", len(result.Tasks))
	}

	// Check first task
	task1 := result.Tasks[0]
	if task1.ID != "TASK-001" {
		t.Errorf("Expected task ID TASK-001, got %s", task1.ID)
	}
	if task1.Title != "Implement User Authentication" {
		t.Errorf("Expected title 'Implement User Authentication', got %s", task1.Title)
	}
	if task1.Status != storage.TaskStatusTodo {
		t.Errorf("Expected status todo, got %s", task1.Status)
	}

	// Check description contains outcome and criteria
	if task1.Description == "" {
		t.Error("Expected non-empty description")
	}

	// Check warnings about placeholder story
	if len(result.Warnings) == 0 {
		t.Error("Expected warning about placeholder story")
	}
}

func TestImportFromBriefs_WithStoryID(t *testing.T) {
	tmpDir := t.TempDir()
	briefsDir := filepath.Join(tmpDir, ".gurgeh", "briefs", "PRD-001")
	if err := os.MkdirAll(briefsDir, 0o755); err != nil {
		t.Fatal(err)
	}

	brief := `# Test Task

## Outcome
Test outcome.

## Acceptance Criteria
- [ ] Test criterion
`
	if err := os.WriteFile(filepath.Join(briefsDir, "BRIEF-001-test.md"), []byte(brief), 0o644); err != nil {
		t.Fatal(err)
	}

	result, err := ImportFromBriefs(BriefImportOptions{
		Root:    tmpDir,
		SpecID:  "PRD-001",
		StoryID: "STORY-EXISTING",
	})
	if err != nil {
		t.Fatalf("ImportFromBriefs failed: %v", err)
	}

	if result.StoryID != "STORY-EXISTING" {
		t.Errorf("Expected story ID 'STORY-EXISTING', got %s", result.StoryID)
	}

	if len(result.Warnings) != 0 {
		t.Errorf("Expected no warnings when story specified, got %d", len(result.Warnings))
	}
}

func TestImportFromBriefs_NotFound(t *testing.T) {
	tmpDir := t.TempDir()

	_, err := ImportFromBriefs(BriefImportOptions{
		Root:   tmpDir,
		SpecID: "NONEXISTENT",
	})
	if err == nil {
		t.Error("Expected error for nonexistent briefs, got nil")
	}
}

func TestExtractBriefTitle(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"# Simple Title\n\nContent", "Simple Title"},
		{"# Title With Spaces   \n", "Title With Spaces"},
		{"No heading here", ""},
		{"## Second Level\n", ""},
		{"# First\n# Second\n", "First"},
	}

	for _, tc := range tests {
		result := extractBriefTitle(tc.input)
		if result != tc.expected {
			t.Errorf("extractBriefTitle(%q) = %q, expected %q", tc.input[:min(30, len(tc.input))], result, tc.expected)
		}
	}
}

func TestExtractSection(t *testing.T) {
	text := `# Title

## Outcome
This is the outcome.
It spans multiple lines.

## Acceptance Criteria
- [ ] First
- [ ] Second
`

	outcome := extractSection(text, "Outcome")
	if outcome != "This is the outcome.\nIt spans multiple lines." {
		t.Errorf("extractSection(Outcome) = %q", outcome)
	}

	criteria := extractSection(text, "Acceptance Criteria")
	if criteria == "" {
		t.Error("extractSection(Acceptance Criteria) returned empty")
	}
}

func TestExtractCriteria(t *testing.T) {
	text := `## Acceptance Criteria
- [ ] First criterion
- [x] Completed criterion
- [ ] Third criterion
`
	criteria := extractCriteria(text)
	if len(criteria) != 3 {
		t.Errorf("Expected 3 criteria, got %d", len(criteria))
	}
	if criteria[0] != "First criterion" {
		t.Errorf("Expected 'First criterion', got %q", criteria[0])
	}
}

func TestGenerateTaskID(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"BRIEF-001-implement-auth.md", "TASK-001"},
		{"BRIEF-042-something.md", "TASK-042"},
		{"random-file.md", "TASK-RANDOM-FILE"},
	}

	for _, tc := range tests {
		result := generateTaskID(tc.input)
		if result != tc.expected {
			t.Errorf("generateTaskID(%q) = %q, expected %q", tc.input, result, tc.expected)
		}
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
