package brief

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/mistakeknot/autarch/internal/gurgeh/project"
	"github.com/mistakeknot/autarch/internal/gurgeh/specs"
)

// Brief describes an outcome for Claude Code to achieve.
type Brief struct {
	Title    string   `json:"title"`    // What to build
	Outcome  string   `json:"outcome"`  // What success looks like
	Criteria []string `json:"criteria"` // How to verify it's done
}

// DecomposeResult is the JSON response from Claude Code.
type DecomposeResult struct {
	Briefs []Brief `json:"briefs"`
}

// Decompose calls Claude Code to break a spec into atomic briefs.
func Decompose(ctx context.Context, spec *specs.Spec, workingDir string) ([]Brief, error) {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Minute)
	defer cancel()

	prompt := buildPrompt(spec)

	cmd := exec.CommandContext(ctx, "claude",
		"-p", prompt,
		"--output-format", "json",
		"--print",
	)
	cmd.Dir = workingDir

	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("claude failed: %w\nstderr: %s", err, exitErr.Stderr)
		}
		return nil, fmt.Errorf("claude failed: %w", err)
	}

	var result DecomposeResult
	if err := json.Unmarshal(out, &result); err != nil {
		// Try extracting JSON from markdown fence
		extracted := extractJSON(string(out))
		if extracted != "" {
			if err := json.Unmarshal([]byte(extracted), &result); err == nil {
				return result.Briefs, nil
			}
		}
		return nil, fmt.Errorf("failed to parse response: %w", err)
	}

	return result.Briefs, nil
}

// SaveBriefs writes each brief as a markdown file.
func SaveBriefs(specID string, briefs []Brief) error {
	return SaveBriefsAt(".", specID, briefs)
}

// SaveBriefsAt writes each brief as a markdown file under the given project root.
func SaveBriefsAt(root string, specID string, briefs []Brief) error {
	dir := filepath.Join(project.BriefsDir(root), specID)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create briefs directory: %w", err)
	}

	for i, b := range briefs {
		filename := fmt.Sprintf("BRIEF-%03d-%s.md", i+1, slug(b.Title))
		content := formatBrief(b)
		path := filepath.Join(dir, filename)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write brief %s: %w", filename, err)
		}
	}

	return nil
}

func buildPrompt(spec *specs.Spec) string {
	// Build requirements list
	var reqs strings.Builder
	for _, r := range spec.Requirements {
		reqs.WriteString("- " + r + "\n")
	}

	// Build CUJs list
	var cujs strings.Builder
	for _, cuj := range spec.CriticalUserJourneys {
		cujs.WriteString(fmt.Sprintf("- %s: %s\n", cuj.ID, cuj.Title))
		for _, step := range cuj.Steps {
			cujs.WriteString("  - " + step + "\n")
		}
	}

	// Build acceptance criteria
	var acceptance strings.Builder
	for _, ac := range spec.Acceptance {
		acceptance.WriteString(fmt.Sprintf("- %s: %s\n", ac.ID, ac.Description))
	}

	return fmt.Sprintf(`Decompose this PRD spec into atomic implementation briefs.

# Spec: %s
Title: %s

## Summary
%s

## Requirements
%s

## Critical User Journeys
%s

## Acceptance Criteria
%s

# Instructions
Break this into atomic briefs. Each brief should be:
1. Completable in one Claude Code session
2. Independently testable
3. Focused on a single outcome

Return JSON with this structure:
{
  "briefs": [
    {
      "title": "Imperative action title",
      "outcome": "What success looks like - the end state",
      "criteria": ["Verifiable check 1", "Verifiable check 2"]
    }
  ]
}

Create one brief per CUJ, or per major requirement if no CUJs exist.
Order briefs by dependencies (do foundational work first).`,
		spec.ID, spec.Title, spec.Summary, reqs.String(), cujs.String(), acceptance.String())
}

func formatBrief(b Brief) string {
	var criteria strings.Builder
	for _, c := range b.Criteria {
		criteria.WriteString("- [ ] " + c + "\n")
	}

	return fmt.Sprintf(`# %s

## Outcome
%s

## Acceptance Criteria
%s
---
*Brief generated by Gurgeh. Execute with: claude -p "$(cat this-file.md)"*
`, b.Title, b.Outcome, criteria.String())
}

// slug converts a title to a URL-safe filename component.
func slug(s string) string {
	s = strings.ToLower(s)
	s = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if len(s) > 40 {
		s = s[:40]
	}
	return s
}

// extractJSON extracts JSON from markdown code fences.
var jsonFenceRe = regexp.MustCompile(`(?s)` + "```" + `(?:json)?\s*\n?(\{.*?\})\s*` + "```")

func extractJSON(text string) string {
	matches := jsonFenceRe.FindStringSubmatch(text)
	if len(matches) > 1 {
		return strings.TrimSpace(matches[1])
	}
	// Fallback: find first { to last }
	start := strings.Index(text, "{")
	end := strings.LastIndex(text, "}")
	if start >= 0 && end > start {
		return text[start : end+1]
	}
	return ""
}
