#!/bin/bash
# Run by the coordinator as mk (never root):
#   scripts/home-build-root-package.sh --commit <full 40-hex sha> [--thread thr_...] [--repo DIR] [--out-dir DIR]
# Reads the five Home upgrade/restore files from the given commit object (no HEAD, no refs, no replace objects) and emits ONE
# self-contained root script, home-v3-run-<sha12>.sh, with the files embedded base64 and each sha256 embedded in its text.
# The generated script uses no git and no checkout content at run time. It is the only trusted source for root: nothing in
# a checkout is ever run with sudo. Prints the sha256 of the whole generated script so a reader can compare.
set -euo pipefail
FILES="home-upgrade-v3.sh home-upgrade-v3.bash home-restore-v2.sh home-restore-v2.bash home-common.bash"
COMMIT=; THREAD=thr_uqy4fzn88x; REPO=.; OUT=.
while [ $# -gt 0 ]; do
  case "$1" in
    --commit) COMMIT=${2:?}; shift 2 ;;
    --thread) THREAD=${2:?}; shift 2 ;;
    --repo) REPO=${2:?}; shift 2 ;;
    --out-dir) OUT=${2:?}; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 64 ;;
  esac
done
[[ "$COMMIT" =~ ^[0-9a-f]{40}$ ]] || { echo "--commit must be a full 40-hex lowercase commit sha (no HEAD, no ref names)" >&2; exit 64; }
[[ "$THREAD" =~ ^thr_[a-z0-9]+$ ]] || { echo "--thread must look like thr_<id>" >&2; exit 64; }
[ "$(id -u)" != 0 ] || { echo "run as mk, not root" >&2; exit 64; }
G=(git --no-replace-objects -C "$REPO")
[ "$("${G[@]}" cat-file -t "$COMMIT")" = commit ] || { echo "$COMMIT is not a commit object" >&2; exit 65; }
[ "$("${G[@]}" rev-parse --verify "$COMMIT")" = "$COMMIT" ] || { echo "rev-parse of $COMMIT does not equal itself" >&2; exit 65; }
SHA12=${COMMIT:0:12}
mkdir -p "$OUT"
OUTFILE=$OUT/home-v3-run-$SHA12.sh
TMP=$(mktemp "$OUT/.home-v3-run.XXXXXX")
trap 'rm -f "$TMP"' EXIT
{
cat <<'HEAD'
#!/bin/sh
# GENERATED by scripts/home-build-root-package.sh. Self-contained: no git, no checkout content at run time.
# Install it root-owned first, then compare, then run (a mk-writable file must never be what sudo executes):
#   sudo install -o root -g root -m 0700 <this file> /root/@NAME@ && sudo sha256sum /root/@NAME@   (compare with the sha256 printed at build)
#   sudo /root/@NAME@ --plugin <v3 build dir>          (installs the copy and dry-runs: nothing is changed)
#   sudo /root/@NAME@ --plugin <v3 build dir> --go     (the real upgrade)
# Re-executes itself under env -i (dash reads no BASH_ENV; ENV only for interactive shells).
if [ "${1:-}" != --clean-env ]; then
  exec /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin HOME_V3_TEST_DEST="${HOME_V3_TEST_DEST:-}" \
    HOME_V3_TEST_BB="${HOME_V3_TEST_BB:-}" HOME_V3_TEST_LAUNCHER_ARGS="${HOME_V3_TEST_LAUNCHER_ARGS:-}" /bin/sh "$0" --clean-env "$@"
fi
shift
HEAD
for f in $FILES; do
  fn=$(printf '%s' "$f" | tr '.-' '__')
  printf 'b64_%s() { cat <<'"'"'EOF_B64'"'"'\n' "$fn"
  "${G[@]}" cat-file blob "$COMMIT:scripts/$f" | base64 -w 76
  printf 'EOF_B64\n}\n'
done
printf 'SHA=%s\nSHA12=%s\nTHREAD=%s\nFILES="%s"\nEXPECT="' "$COMMIT" "$SHA12" "$THREAD" "$FILES"
for f in $FILES; do printf '%s  %s\n' "$("${G[@]}" cat-file blob "$COMMIT:scripts/$f" | sha256sum | cut -d' ' -f1)" "$f"; done
printf '"\n'
cat <<'MAIN'
set -eu
umask 022
# The reports go out through bb, which spawns with cwd: process.cwd(); root's cwd (/root) is unreadable to mk (EACCES).
: "${HOME_V3_TEST_DEST:=}" "${HOME_V3_TEST_BB:=}" "${HOME_V3_TEST_LAUNCHER_ARGS:=}"
TESTMODE=0
if [ -n "$HOME_V3_TEST_DEST$HOME_V3_TEST_BB$HOME_V3_TEST_LAUNCHER_ARGS" ]; then
  [ "$(id -u)" != 0 ] || { echo "HOME_V3_TEST_* is refused as root" >&2; exit 64; }
  TESTMODE=1
fi
if [ "$TESTMODE" = 1 ]; then DEST=$HOME_V3_TEST_DEST; OWN=; else
  [ "$(id -u)" = 0 ] || { echo "run as root (euid 0)" >&2; exit 64; }
  DEST=/usr/local/libexec/home-v3-$SHA12; OWN="-o root -g root"
fi
PLUGIN=; GO=0
while [ $# -gt 0 ]; do
  case "$1" in
    --plugin) PLUGIN=${2:?}; shift 2 ;;
    --go) GO=1; shift ;;
    *) echo "unknown argument: $1" >&2; exit 64 ;;
  esac
done
[ -n "$PLUGIN" ] || { echo "usage: $0 --plugin <v3 build dir> [--go]" >&2; exit 64; }
case "$DEST" in /*) ;; *) echo "destination must be absolute" >&2; exit 64 ;; esac
case "$PLUGIN" in /*) ;; *) echo "--plugin must be an absolute path" >&2; exit 64 ;; esac
cd /
REPORT=$(mktemp /tmp/home-v3-run.XXXXXX); chmod 0644 "$REPORT"
STAGE=
say() { printf '%s\n' "$*"; printf '%s\n' "$*" >>"$REPORT"; }
finish() {
  rc=$?
  trap - EXIT
  [ -z "$STAGE" ] || rm -rf "$STAGE"
  if [ "$rc" = 0 ]; then say "home-v3-run $SHA12: SUCCESS (exit 0; upgrade $([ "$GO" = 1 ] && echo ran || echo NOT run, dry run only))"
  else say "home-v3-run $SHA12: FAILED (exit $rc)"; fi
  if [ "$TESTMODE" = 1 ]; then
    if [ -n "$HOME_V3_TEST_BB" ]; then "$HOME_V3_TEST_BB" thread tell "$THREAD" --message-file "$REPORT"; else false; fi
  else
    MKHOME=$(getent passwd mk | cut -d: -f6)
    [ -n "$MKHOME" ] && [ -x "$MKHOME/.local/bin/bb" ] && \
    runuser -u mk -- env -i HOME="$MKHOME" USER=mk LOGNAME=mk PATH=/usr/bin:/bin XDG_RUNTIME_DIR="/run/user/$(id -u mk)" \
      "$MKHOME/.local/bin/bb" thread tell "$THREAD" --message-file "$REPORT"
  fi || { echo "report not delivered to $THREAD; report follows (also in $REPORT):" >&2; cat "$REPORT" >&2; }
  exit "$rc"
}
trap finish EXIT
die() { say "$*"; exit "${2:-5}"; }

verify_dir() {  # exact file set, exact sha256 of each
  [ "$(ls -A "$1" | tr '\n' ' ')" = "$(for f in $FILES; do echo "$f"; done | sort | tr '\n' ' ')" ] || return 1
  printf '%s\n' "$EXPECT" | (cd "$1" && sha256sum -c --quiet -) >/dev/null 2>&1
}
mode_of() { case "$1" in *.sh) echo 0755 ;; *) echo 0644 ;; esac; }

p=$DEST
while [ -n "$p" ] && [ "$p" != / ]; do
  [ ! -L "$p" ] || die "refusing: $p is a symlink"
  p=${p%/*}
done
PARENT=${DEST%/*}; [ -n "$PARENT" ] || PARENT=/
[ -d "$PARENT" ] || mkdir -p -m 0755 "$PARENT"
if [ "$TESTMODE" = 0 ]; then
  [ "$(stat -c '%u %g' "$PARENT")" = "0 0" ] && [ $(( 0$(stat -c %a "$PARENT") & 18 )) -eq 0 ] || die "refusing: $PARENT is not root-owned and tight"
fi
if [ -e "$DEST" ]; then
  [ -d "$DEST" ] && verify_dir "$DEST" || die "refusing: $DEST exists with unexpected content"
  if [ "$TESTMODE" = 0 ]; then
    for f in "$DEST" $(for g in $FILES; do echo "$DEST/$g"; done); do
      [ "$(stat -c '%u %g' "$f")" = "0 0" ] && [ $(( 0$(stat -c %a "$f") & 18 )) -eq 0 ] || die "refusing: $f is not root-owned and tight"
    done
  fi
  say "already installed at $DEST (content verified)"
else
  STAGE=$(mktemp -d "$PARENT/.home-v3-stage.XXXXXX")
  chmod 0755 "$STAGE"
  for f in $FILES; do
    fn=$(printf '%s' "$f" | tr '.-' '__')
    ( umask 077; "b64_$fn" | base64 -d >"$STAGE/.in" )
    install $OWN -m "$(mode_of "$f")" "$STAGE/.in" "$STAGE/$f"
    rm -f "$STAGE/.in"
  done
  verify_dir "$STAGE" || die "sha256 verification of the staged files failed; nothing installed"
  mv -T "$STAGE" "$DEST"; STAGE=
  say "installed root-owned copy at $DEST (commit $SHA, sha256 verified)"
fi

LX=${HOME_V3_TEST_LAUNCHER_ARGS:-}
set -f
say "== upgrade --check (nothing is changed)"
"$DEST/home-upgrade-v3.sh" --thread "$THREAD" --plugin "$PLUGIN" --check $LX
if [ "$GO" = 1 ]; then
  say "== upgrade (--go)"
  "$DEST/home-upgrade-v3.sh" --thread "$THREAD" --plugin "$PLUGIN" $LX
else
  say "dry run only. Inspect, then rerun with --go."
fi
say "restore, if needed (separate command): sudo $DEST/home-restore-v2.sh --thread $THREAD --repo <Autarch checkout> [--backup <path>]"
MAIN
} >"$TMP"
sed -i "s/@NAME@/home-v3-run-$SHA12.sh/g" "$TMP"
chmod 0644 "$TMP"
mv -f "$TMP" "$OUTFILE"; trap - EXIT
echo "$OUTFILE"
echo "sha256 $(sha256sum "$OUTFILE" | cut -d' ' -f1)"
